name: auto-merge

on:
  pull_request:

permissions: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          target: minor
          command: squash and merge
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE_PAT }}
